"""Adding isShown column

Revision ID: 0294a59abe48
Revises: cc0e6cd09a4c
Create Date: 2024-12-16 11:14:42.785042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0294a59abe48'
down_revision: Union[str, None] = 'cc0e6cd09a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdg_coin_wallet_histories', sa.Column('is_shown', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sdg_coin_wallet_histories', 'is_shown')
    # ### end Alembic commands ###
