"""Adding scenario type to SDGLabelDecision

Revision ID: 18f696475eb6
Revises: fe2fdd8a542b
Create Date: 2025-01-24 15:11:36.564348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18f696475eb6'
down_revision: Union[str, None] = 'fe2fdd8a542b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdg_label_decisions', sa.Column('scenario_type', sa.Enum('CONFIRM', 'TIEBREAKER', 'INVESTIGATE', 'EXPLORE', 'NOT_ENOUGH_VOTES', 'NO_SPECIFIC_SCENARIO', name='scenariotype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sdg_label_decisions', 'scenario_type')
    # ### end Alembic commands ###
