"""Add extras for sdg goals

Revision ID: 29df6270728a
Revises: 33010b178e40
Create Date: 2025-01-29 15:16:54.967773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '29df6270728a'
down_revision: Union[str, None] = '33010b178e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdg_goals', sa.Column('short_title', sa.String(length=100), nullable=False))
    op.add_column('sdg_goals', sa.Column('keywords', sa.String(length=255), nullable=False))
    op.add_column('sdg_goals', sa.Column('explanation', mysql.LONGTEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sdg_goals', 'explanation')
    op.drop_column('sdg_goals', 'keywords')
    op.drop_column('sdg_goals', 'short_title')
    # ### end Alembic commands ###
