"""Add publication_id to SDGLabelDecision and SDGUserLabel

Revision ID: 48f1369c7a32
Revises: 29df6270728a
Create Date: 2025-01-31 15:24:51.604039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f1369c7a32'
down_revision: Union[str, None] = '29df6270728a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdg_label_decisions', sa.Column('publication_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sdg_label_decisions', 'publications', ['publication_id'], ['publication_id'])
    op.add_column('sdg_user_labels', sa.Column('publication_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sdg_user_labels', 'publications', ['publication_id'], ['publication_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sdg_user_labels', type_='foreignkey')
    op.drop_column('sdg_user_labels', 'publication_id')
    op.drop_constraint(None, 'sdg_label_decisions', type_='foreignkey')
    op.drop_column('sdg_label_decisions', 'publication_id')
    # ### end Alembic commands ###
