"""Updated Vote

Revision ID: 57d57ade7265
Revises: 40dcc2c7ef9d
Create Date: 2025-01-20 16:15:33.659142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d57ade7265'
down_revision: Union[str, None] = '40dcc2c7ef9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'updated_at')
    # ### end Alembic commands ###
