"""Adding SDGXPBanks and SDGCoinWallets

Revision ID: 58a824784685
Revises: c638bae69cae
Create Date: 2024-12-09 14:37:17.065920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a824784685'
down_revision: Union[str, None] = 'c638bae69cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdg_coin_wallets',
    sa.Column('sdg_coin_wallet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_coins', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('sdg_coin_wallet_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_sdg_coin_wallets_sdg_coin_wallet_id'), 'sdg_coin_wallets', ['sdg_coin_wallet_id'], unique=False)
    op.create_table('sdg_xp_banks',
    sa.Column('sdg_xp_bank_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('sdg_xp_bank_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_sdg_xp_banks_sdg_xp_bank_id'), 'sdg_xp_banks', ['sdg_xp_bank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sdg_xp_banks_sdg_xp_bank_id'), table_name='sdg_xp_banks')
    op.drop_table('sdg_xp_banks')
    op.drop_index(op.f('ix_sdg_coin_wallets_sdg_coin_wallet_id'), table_name='sdg_coin_wallets')
    op.drop_table('sdg_coin_wallets')
    # ### end Alembic commands ###
