"""Update decidedAt from SDGLabelDecision

Revision ID: 602781c4750e
Revises: a74ef7735570
Create Date: 2025-02-10 13:46:53.137910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '602781c4750e'
down_revision: Union[str, None] = 'a74ef7735570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sdg_label_decisions', 'decided_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sdg_label_decisions', 'decided_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
