"""Adding Collections

Revision ID: 6d428a0c70ad
Revises: 831cacc1fa4e
Create Date: 2025-01-21 13:33:52.743711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d428a0c70ad'
down_revision: Union[str, None] = '831cacc1fa4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('collection_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('representation', sa.Text(), nullable=False),
    sa.Column('aspect1', sa.Text(), nullable=False),
    sa.Column('aspect2', sa.Text(), nullable=False),
    sa.Column('aspect3', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.add_column('publications', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'publications', 'collections', ['collection_id'], ['collection_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.drop_column('publications', 'collection_id')
    op.drop_table('collections')
    # ### end Alembic commands ###
