"""Changing annotations

Revision ID: 733326aabde3
Revises: 11d048a8d8d5
Create Date: 2025-01-20 09:11:00.452973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '733326aabde3'
down_revision: Union[str, None] = '11d048a8d8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('decision_id', sa.Integer(), nullable=True))
    op.alter_column('annotations', 'sdg_user_label_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'annotations', 'sdg_label_decisions', ['decision_id'], ['decision_id'])
    op.alter_column('users', 'nickname',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nickname',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.alter_column('annotations', 'sdg_user_label_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('annotations', 'decision_id')
    # ### end Alembic commands ###
