"""Adding Collections topic identifier

Revision ID: 8aed73470772
Revises: 53afdb05cef1
Create Date: 2025-01-21 14:07:49.629612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aed73470772'
down_revision: Union[str, None] = '53afdb05cef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'collections', ['topic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='unique')
    op.drop_column('collections', 'topic_id')
    # ### end Alembic commands ###
