"""Adding multiple XPs in SDGXPBanks

Revision ID: 90c750de06dc
Revises: 6bb072f2f4a8
Create Date: 2024-12-10 08:20:07.131803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c750de06dc'
down_revision: Union[str, None] = '6bb072f2f4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdg_xp_bank_histories', sa.Column('sdg', sa.Enum('SDG_1', 'SDG_2', 'SDG_3', 'SDG_4', 'SDG_5', 'SDG_6', 'SDG_7', 'SDG_8', 'SDG_9', 'SDG_10', 'SDG_11', 'SDG_12', 'SDG_13', 'SDG_14', 'SDG_15', 'SDG_16', 'SDG_17', name='sdgenum'), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_1_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_2_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_3_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_4_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_5_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_6_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_7_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_8_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_9_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_10_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_11_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_12_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_13_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_14_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_15_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_16_xp', sa.Float(), nullable=False))
    op.add_column('sdg_xp_banks', sa.Column('sdg_17_xp', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sdg_xp_banks', 'sdg_17_xp')
    op.drop_column('sdg_xp_banks', 'sdg_16_xp')
    op.drop_column('sdg_xp_banks', 'sdg_15_xp')
    op.drop_column('sdg_xp_banks', 'sdg_14_xp')
    op.drop_column('sdg_xp_banks', 'sdg_13_xp')
    op.drop_column('sdg_xp_banks', 'sdg_12_xp')
    op.drop_column('sdg_xp_banks', 'sdg_11_xp')
    op.drop_column('sdg_xp_banks', 'sdg_10_xp')
    op.drop_column('sdg_xp_banks', 'sdg_9_xp')
    op.drop_column('sdg_xp_banks', 'sdg_8_xp')
    op.drop_column('sdg_xp_banks', 'sdg_7_xp')
    op.drop_column('sdg_xp_banks', 'sdg_6_xp')
    op.drop_column('sdg_xp_banks', 'sdg_5_xp')
    op.drop_column('sdg_xp_banks', 'sdg_4_xp')
    op.drop_column('sdg_xp_banks', 'sdg_3_xp')
    op.drop_column('sdg_xp_banks', 'sdg_2_xp')
    op.drop_column('sdg_xp_banks', 'sdg_1_xp')
    op.drop_column('sdg_xp_bank_histories', 'sdg')
    # ### end Alembic commands ###
