"""Add SDGRanks

Revision ID: 97620ee0a6a0
Revises: 48f1369c7a32
Create Date: 2025-02-08 14:46:34.509229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97620ee0a6a0'
down_revision: Union[str, None] = '48f1369c7a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdg_ranks',
    sa.Column('rank_id', sa.Integer(), nullable=False),
    sa.Column('sdg_goal_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('xp_required', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('rank_id')
    )
    op.create_index(op.f('ix_sdg_ranks_rank_id'), 'sdg_ranks', ['rank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sdg_ranks_rank_id'), table_name='sdg_ranks')
    op.drop_table('sdg_ranks')
    # ### end Alembic commands ###
