"""Update SDGRanks

Revision ID: a74ef7735570
Revises: 97620ee0a6a0
Create Date: 2025-02-08 14:55:26.349476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74ef7735570'
down_revision: Union[str, None] = '97620ee0a6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdg_ranks', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('sdg_ranks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sdg_ranks', 'updated_at')
    op.drop_column('sdg_ranks', 'created_at')
    # ### end Alembic commands ###
