"""Changing constraint for SDGUserLabels

Revision ID: bdc1165d6ea0
Revises: 18f696475eb6
Create Date: 2025-01-24 17:28:49.310819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc1165d6ea0'
down_revision: Union[str, None] = '18f696475eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
