"""Changing SDGUserLabels

Revision ID: bf4dcaea89a2
Revises: 90c750de06dc
Create Date: 2024-12-14 11:12:31.988343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf4dcaea89a2'
down_revision: Union[str, None] = '90c750de06dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdg_user_labels', sa.Column('abstract_section', sa.String(length=1000), nullable=True))
    op.add_column('sdg_user_labels', sa.Column('comment', sa.String(length=1000), nullable=True))
    op.drop_column('sdg_user_labels', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdg_user_labels', sa.Column('description', mysql.VARCHAR(length=1000), nullable=True))
    op.drop_column('sdg_user_labels', 'comment')
    op.drop_column('sdg_user_labels', 'abstract_section')
    # ### end Alembic commands ###
