"""Adding Summaries

Revision ID: c638bae69cae
Revises: d5233ac79c3a
Create Date: 2024-12-06 11:11:45.341153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c638bae69cae'
down_revision: Union[str, None] = 'd5233ac79c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.publication_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('publication_id')
    )
    op.create_index(op.f('ix_summaries_summary_id'), 'summaries', ['summary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_summary_id'), table_name='summaries')
    op.drop_table('summaries')
    # ### end Alembic commands ###
