"""Text columns and isShown column

Revision ID: cc0e6cd09a4c
Revises: bf4dcaea89a2
Create Date: 2024-12-16 11:13:21.812980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc0e6cd09a4c'
down_revision: Union[str, None] = 'bf4dcaea89a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sdg_coin_wallet_histories', 'reason',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('sdg_user_labels', 'abstract_section',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('sdg_user_labels', 'comment',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('sdg_xp_bank_histories', sa.Column('is_shown', sa.Boolean(), nullable=True))
    op.alter_column('sdg_xp_bank_histories', 'reason',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sdg_xp_bank_histories', 'reason',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('sdg_xp_bank_histories', 'is_shown')
    op.alter_column('sdg_user_labels', 'comment',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('sdg_user_labels', 'abstract_section',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('sdg_coin_wallet_histories', 'reason',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
