"""Adding facts

Revision ID: d5233ac79c3a
Revises: 6bf8f59aa151
Create Date: 2024-12-02 16:57:45.336161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5233ac79c3a'
down_revision: Union[str, None] = '6bf8f59aa151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facts',
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.publication_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('fact_id'),
    sa.UniqueConstraint('publication_id')
    )
    op.create_index(op.f('ix_facts_fact_id'), 'facts', ['fact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facts_fact_id'), table_name='facts')
    op.drop_table('facts')
    # ### end Alembic commands ###
